### ISSUE TITLE
Concatenation of weighted avg + covariance components

### ISSUE THREAD

**Issue by tholor** [BinWang28/Sentence-Embedding-S3E#1]
Hey @BinWang28 , 

Thanks for providing code to your paper - very much appreciated!
Your approach sounds interesting and we would like to benchmark it for an industrial application. 

One question that occurred to us while digging through the code: 
Is your method actually proposing to always concatenate the weighted avg of word embeddings + the "new", proposed covariance components?

For low numbers of clusters (e.g. the default 10), 300 out of 355 dims of the vector are then actually occupied by the weighted avg. 

This is the related part of the code: 

https://github.com/BinWang28/Sentence-Embedding-S3E/blob/b7864707a610392e5e6b9135e4d3c5f06538154a/utils.py#L193-L198

and then

https://github.com/BinWang28/Sentence-Embedding-S3E/blob/b7864707a610392e5e6b9135e4d3c5f06538154a/utils.py#L218

I couldn't find this being mentioned in the paper. Maybe I missed it?

**Comment by BinWang28** [comment]
@tholor 
You're right. We always concatenating the weighted averaging of word embedding.
